name: Update Website with GIFs

on:
  repository_dispatch:
    types: [update-gifs]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout website code
      uses: actions/checkout@v2

    - name: Remove old GIFs
      run: |
        # Assuming the GIFs are stored in a directory named 'constellationbot_gifs' in your Jekyll site's 'Figures' directory.
        rm -rf Figures/constellationbot_gifs

    - name: Download GIF artifact
      run: |
        curl -L -o artifact.zip -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" "${{ github.event.client_payload.artifact_url }}"
        unzip artifact.zip -d Figures/constellationbot_gifs
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "<your-email>@users.noreply.github.com"
        git add -A
        git commit -m "Update GIFs"
        git push