name: Update Website with GIFs

on:
  repository_dispatch:
    types: [update-gifs]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout website code
      uses: actions/checkout@master

    - name: Remove old GIFs
      run: |
        rm -rf Figures/constellationbot_gifs

    - name: Download GIF artifact
      run: |
        curl -L -o artifact.zip -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" "${{ github.event.client_payload.artifact_url }}"
        unzip artifact.zip -d Figures/constellationbot_gifs
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Setup Git and Push Changes
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "CharlesPlusC@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/CharlesPlusC/CharlesPlusC.github.io.git
        git add -A
        git commit -m "Update GIFs"
        git push -v
